auth_kind: serviceaccount
compose: {ansible_host: 'networkInterfaces[0].accessConfigs[0].natIP'}
groups: {prod: '''prod'' in (labels|list)', running: '''RUNNING'' in status', stage: '''stage''
    in (labels|list)'}
hostnames: [name]
keyed_groups:
- {key: machineType}
plugin: gcp_compute
projects: [ci-cd-example-308115]
regions: [europe-west3]
service_account_file: servisce-file.json
