# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.10
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: target
        path: staging

    #    - name: Maven Package
#      run: mvn -B clean package -DskipTests
#    - name: Maven Verify
#      run: mvn -B clean verify

    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml

  publish:

    runs-on: ubuntu-latest

    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - run: ls -la target
    #- name: Build & push Docker image
     # uses: mr-smithers-excellent/docker-build-push@v5
      #with:
       # image: bobwithb/myfirstapp
        #registry: docker.io
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}
